version: '3'
services:
    app:
        container_name: sample-app
        image: sample-app
        restart: always
        build:
            context: .
            target: dev
            dockerfile: ./app/Dockerfile
            args:
                GOPRIVATE: ${GOPRIVATE}
        environment:
            GOPRIVATE: github.com/yagrush
        ports:
            - 2349:2345
            - 8083:8080
        tty: true
        volumes:
            - ./app:/app

    db:
        container_name: sample-db
        image: sample-db
        restart: always
        build:
            context: .
            dockerfile: ./db/Dockerfile
        ports:
            - 3309:3306
        volumes:
            - ./db/conf/:/etc/mysql/conf.d
            - sample-db-local:/var/lib/mysql
            - ./db/log/:/var/log
        user: 1000:1000
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: sample
            MYSQL_USER: sample
            MYSQL_PASSWORD: sample
            # TZ: ${TZ} # world wideなサービスならUTC+0にしたい

volumes:
    # 名前付きボリュームを消すと docker-entrypoint-initdb.d がまた走る
    sample-db-local: